-- MySQL Script generated by MySQL Workbench
-- Sat May 16 14:31:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Inmobilaria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Inmobilaria` ;

-- -----------------------------------------------------
-- Schema Inmobilaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Inmobilaria` DEFAULT CHARACTER SET utf8 ;
USE `Inmobilaria` ;

-- -----------------------------------------------------
-- Table `Inmobilaria`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobilaria`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `Dni` VARCHAR(18) NOT NULL,
  `Nombre` VARCHAR(70) NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Telefono` VARCHAR(30) NOT NULL,
  `Usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inmobilaria`.`Propiedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobilaria`.`Propiedad` (
  `idPropiedad` INT NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Tamaño` VARCHAR(45) NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `PrecioAlquiler` DOUBLE NOT NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idPropiedad`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `Inmobilaria`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inmobilaria`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobilaria`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL,
  `Telefono` VARCHAR(30) NOT NULL,
  `Dni` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `DNI` (`Dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inmobilaria`.`DueñosPropiedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobilaria`.`DueñosPropiedad` (
  `idPropiedad` INT NOT NULL,
  `DniDueño` VARCHAR(18) NOT NULL,
  INDEX `idPropiedad_idx` (`idPropiedad` ASC) VISIBLE,
  INDEX `idCliente_idx` (`DniDueño` ASC) VISIBLE,
  CONSTRAINT `idPropiedad`
    FOREIGN KEY (`idPropiedad`)
    REFERENCES `Inmobilaria`.`Propiedad` (`idPropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DniDueño`)
    REFERENCES `Inmobilaria`.`Cliente` (`Dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inmobilaria`.`Alquiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobilaria`.`Alquiler` (
  `idAlquiler` INT NOT NULL AUTO_INCREMENT,
  `DniTitular` VARCHAR(18) NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL,
  `Telefono` VARCHAR(30) NOT NULL,
  `FechaContrato` DATE NOT NULL,
  `PrecioAlquiler` DOUBLE NOT NULL,
  `idPropiedad` INT NOT NULL,
  `FechaCobro` DATE NOT NULL,
  `FechaPago` DATE NOT NULL,
  PRIMARY KEY (`idAlquiler`),
  INDEX `idPropiedad_idx` (`idPropiedad` ASC) VISIBLE,
  INDEX `DniTitular_idx` (`DniTitular` ASC) VISIBLE,
  CONSTRAINT `Propiedad`
    FOREIGN KEY (`idPropiedad`)
    REFERENCES `Inmobilaria`.`Propiedad` (`idPropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DniTitular`
    FOREIGN KEY (`DniTitular`)
    REFERENCES `Inmobilaria`.`Cliente` (`Dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inmobilaria`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobilaria`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `Comprador` VARCHAR(70) NOT NULL,
  `Telefono` VARCHAR(30) NOT NULL,
  `DireccionComprador` VARCHAR(150) NOT NULL,
  `idEmpleado` INT NOT NULL,
  `FechaVenta` DATE NOT NULL,
  `idPropiedad` INT NOT NULL,
  `PrecioInicial` DOUBLE NOT NULL,
  `PrecioFinal` DOUBLE NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  INDEX `Propiedad_idx` (`idPropiedad` ASC) VISIBLE,
  CONSTRAINT `Empleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `Inmobilaria`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idsPropiedad`
    FOREIGN KEY (`idPropiedad`)
    REFERENCES `Inmobilaria`.`Propiedad` (`idPropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inmobilaria`.`Visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inmobilaria`.`Visita` (
  `idVisita` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `NombreCliente` VARCHAR(70) NOT NULL,
  `Comentario` VARCHAR(300) NOT NULL,
  `FechaVisita` DATE NOT NULL,
  PRIMARY KEY (`idVisita`),
  INDEX `idEmpleado_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `EmpleadoVisita`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `Inmobilaria`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
