/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.CardLayout;

/**
 *
 * @author Gerardo GC
 */
public class vistaPrincipal extends javax.swing.JFrame {

    public CardLayout C = new CardLayout();
    
    public vistaPrincipal() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotones = new javax.swing.JPanel();
        btnPropiedades = new javax.swing.JButton();
        btnPropConsulta = new javax.swing.JButton();
        btnPropAlta = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnClientAlta = new javax.swing.JButton();
        btnClientConsulta = new javax.swing.JButton();
        btnVendedores = new javax.swing.JButton();
        btnVendAlta = new javax.swing.JButton();
        btnVendConsulta = new javax.swing.JButton();
        pnlAcciones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlBotones.setBackground(new java.awt.Color(112, 173, 71));
        pnlBotones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlBotones.setPreferredSize(new java.awt.Dimension(300, 864));

        btnPropiedades.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPropiedades.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/home.png"))); // NOI18N
        btnPropiedades.setText("Propiedades");
        btnPropiedades.setBorderPainted(false);
        btnPropiedades.setContentAreaFilled(false);
        btnPropiedades.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPropiedades.setFocusPainted(false);

        btnPropConsulta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPropConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnPropConsulta.setText("Consulta");
        btnPropConsulta.setBorderPainted(false);
        btnPropConsulta.setContentAreaFilled(false);
        btnPropConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPropConsulta.setFocusPainted(false);

        btnPropAlta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPropAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnPropAlta.setText("Alta / Baja");
        btnPropAlta.setBorderPainted(false);
        btnPropAlta.setContentAreaFilled(false);
        btnPropAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPropAlta.setFocusPainted(false);

        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/socialWhite.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorderPainted(false);
        btnClientes.setContentAreaFilled(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClientes.setFocusPainted(false);

        btnClientAlta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnClientAlta.setText("Alta / Baja");
        btnClientAlta.setBorderPainted(false);
        btnClientAlta.setContentAreaFilled(false);
        btnClientAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientAlta.setFocusPainted(false);

        btnClientConsulta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnClientConsulta.setText("Consulta");
        btnClientConsulta.setBorderPainted(false);
        btnClientConsulta.setContentAreaFilled(false);
        btnClientConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientConsulta.setFocusPainted(false);

        btnVendedores.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVendedores.setForeground(new java.awt.Color(255, 255, 255));
        btnVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/business.png"))); // NOI18N
        btnVendedores.setText("Vendedores");
        btnVendedores.setBorderPainted(false);
        btnVendedores.setContentAreaFilled(false);
        btnVendedores.setFocusPainted(false);

        btnVendAlta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVendAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnVendAlta.setText("Alta / Baja");
        btnVendAlta.setBorderPainted(false);
        btnVendAlta.setContentAreaFilled(false);
        btnVendAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendAlta.setFocusPainted(false);

        btnVendConsulta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVendConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnVendConsulta.setText("Consulta");
        btnVendConsulta.setBorderPainted(false);
        btnVendConsulta.setContentAreaFilled(false);
        btnVendConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendConsulta.setFocusPainted(false);

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnPropAlta)
                        .addComponent(btnPropConsulta)
                        .addComponent(btnPropiedades)
                        .addComponent(btnClientAlta)
                        .addComponent(btnClientConsulta)
                        .addComponent(btnVendAlta)
                        .addComponent(btnVendConsulta))
                    .addComponent(btnClientes)
                    .addComponent(btnVendedores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnPropiedades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPropConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnPropAlta)
                .addGap(30, 30, 30)
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnClientAlta)
                .addGap(30, 30, 30)
                .addComponent(btnVendedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnVendAlta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBotones, java.awt.BorderLayout.WEST);

        pnlAcciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlAcciones.setPreferredSize(new java.awt.Dimension(811, 864));

        javax.swing.GroupLayout pnlAccionesLayout = new javax.swing.GroupLayout(pnlAcciones);
        pnlAcciones.setLayout(pnlAccionesLayout);
        pnlAccionesLayout.setHorizontalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        pnlAccionesLayout.setVerticalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        getContentPane().add(pnlAcciones, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClientAlta;
    public javax.swing.JButton btnClientConsulta;
    public javax.swing.JButton btnClientes;
    public javax.swing.JButton btnPropAlta;
    public javax.swing.JButton btnPropConsulta;
    public javax.swing.JButton btnPropiedades;
    public javax.swing.JButton btnVendAlta;
    public javax.swing.JButton btnVendConsulta;
    public javax.swing.JButton btnVendedores;
    public javax.swing.JPanel pnlAcciones;
    public javax.swing.JPanel pnlBotones;
    // End of variables declaration//GEN-END:variables
}
