/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.PropiedadesController;
import Modelo.Propiedades;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;

/**
 *
 * @author reymi
 */
public class ConsultaP extends javax.swing.JFrame {
    PropiedadesController controller = new PropiedadesController();
    ArrayList<Propiedades> propiedades;

    /**
     * Creates new form ConsultaP
     */
    public ConsultaP() {
        initComponents();
        propiedades = controller.CargarPropiedades();
        this.TablaDatos = controller.CargarTabla(TablaDatos, propiedades);
    }
    
    public void ActualizarTabla() {
        this.propiedades.clear();
        this.propiedades = controller.CargarPropiedades();
        this.TablaDatos = controller.CargarTabla(TablaDatos, propiedades);
        TablaDatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TablaDatos.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Background = new javax.swing.JPanel();
        Buscar = new javax.swing.JTextField();
        Disponibles = new javax.swing.JRadioButton();
        Vendidas = new javax.swing.JRadioButton();
        Renta = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        BtnEditar = new javax.swing.JButton();
        BtnNuevo = new javax.swing.JButton();
        Todas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        Buscar.setToolTipText("Buscar propiedad");

        Disponibles.setBackground(new java.awt.Color(255, 255, 255));
        Disponibles.setText("Disponibles");
        Disponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisponiblesActionPerformed(evt);
            }
        });

        Vendidas.setBackground(new java.awt.Color(255, 255, 255));
        Vendidas.setText("Vendidas");
        Vendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendidasActionPerformed(evt);
            }
        });

        Renta.setBackground(new java.awt.Color(255, 255, 255));
        Renta.setText("En renta");
        Renta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Consulta de propiedades");

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dirección", "Tipo", "Costo de venta", "Costo de renta", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaDatos);

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnNuevo.setText("Nueva");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        Todas.setBackground(new java.awt.Color(255, 255, 255));
        Todas.setText("Todas");
        Todas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(Disponibles)
                                .addGap(18, 18, 18)
                                .addComponent(Vendidas)
                                .addGap(18, 18, 18)
                                .addComponent(Renta)
                                .addGap(18, 18, 18)
                                .addComponent(Todas)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnNuevo)
                            .addComponent(BtnEditar))
                        .addGap(36, 36, 36))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Disponibles)
                        .addComponent(Vendidas)
                        .addComponent(Renta)
                        .addComponent(Todas))
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(BtnEditar)
                        .addGap(52, 52, 52)
                        .addComponent(BtnNuevo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisponiblesActionPerformed
        // TODO add your handling code here:
        ArrayList<Propiedades> Disponibles = new ArrayList<>();
        for(Propiedades propiedad : propiedades){
            if(propiedad.getEstado().equals("En venta")){
                Disponibles.add(propiedad);
            }
        }
        this.TablaDatos = controller.CargarTabla(TablaDatos, Disponibles);
        TablaDatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TablaDatos.updateUI();
    }//GEN-LAST:event_DisponiblesActionPerformed

    private void VendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendidasActionPerformed
        // TODO add your handling code here:
        ArrayList<Propiedades> Venta = new ArrayList<>();
        for(Propiedades propiedad : propiedades){
            if(propiedad.getEstado().equals("Vendida")){
                Venta.add(propiedad);
            }
        }
        this.TablaDatos = controller.CargarTabla(TablaDatos, Venta);
        TablaDatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TablaDatos.updateUI();
    }//GEN-LAST:event_VendidasActionPerformed

    private void RentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentaActionPerformed
        // TODO add your handling code here:
        ArrayList<Propiedades> Renta = new ArrayList<>();
        for(Propiedades propiedad : propiedades){
            if(propiedad.getEstado().equals("En renta")){
                Renta.add(propiedad);
            }
        }
        this.TablaDatos = controller.CargarTabla(TablaDatos, Renta);
        TablaDatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TablaDatos.updateUI();
    }//GEN-LAST:event_RentaActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // TODO add your handling code here:
        EditarPropiedad editar = new EditarPropiedad();
        editar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        editar.SetPropiedad(propiedades.get(TablaDatos.getSelectedRow()));
        editar.Cargar();
        editar.GetVentanaConsulta(this);
        editar.setVisible(true);
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        // TODO add your handling code here:
        NuevaPropiedad nueva = new NuevaPropiedad();
        nueva.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        nueva.GetVentanaConsulta(this);
        nueva.setVisible(true);
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void TodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodasActionPerformed
        // TODO add your handling code here:
        this.propiedades.clear();
        this.propiedades = controller.CargarPropiedades();
        this.TablaDatos = controller.CargarTabla(TablaDatos, propiedades);
        TablaDatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TablaDatos.updateUI();
    }//GEN-LAST:event_TodasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JTextField Buscar;
    private javax.swing.JRadioButton Disponibles;
    private javax.swing.JRadioButton Renta;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JRadioButton Todas;
    private javax.swing.JRadioButton Vendidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
