/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Gerardo GC
 */
public class vistaPrincipal extends javax.swing.JFrame {
    CardLayout cardLayout;
    ConsultaPropiedad consulta = new ConsultaPropiedad();
    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
        initComponents();
        cardLayout = (CardLayout) (this.PanelVistas.getLayout());
        cardLayout.show(this.PanelVistas, "Consulta");
        this.PanelVistas.add(consulta, "Consulta");
        SwingUtilities.updateComponentTreeUI(this.PanelVistas);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPropiedades = new javax.swing.JButton();
        btnPropConsulta = new javax.swing.JButton();
        BtnNuevaPropiedad = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnClientAlta = new javax.swing.JButton();
        btnClientConsulta = new javax.swing.JButton();
        btnVendedores = new javax.swing.JButton();
        btnVendAlta = new javax.swing.JButton();
        btnVendConsulta = new javax.swing.JButton();
        PanelVistas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(112, 173, 71));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 864));

        btnPropiedades.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPropiedades.setForeground(new java.awt.Color(255, 255, 255));
        btnPropiedades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/home.png"))); // NOI18N
        btnPropiedades.setText("Propiedades");
        btnPropiedades.setContentAreaFilled(false);

        btnPropConsulta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPropConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnPropConsulta.setText("Consulta");
        btnPropConsulta.setContentAreaFilled(false);
        btnPropConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropConsultaActionPerformed(evt);
            }
        });

        BtnNuevaPropiedad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnNuevaPropiedad.setForeground(new java.awt.Color(255, 255, 255));
        BtnNuevaPropiedad.setText("Nueva");
        BtnNuevaPropiedad.setContentAreaFilled(false);
        BtnNuevaPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevaPropiedadActionPerformed(evt);
            }
        });

        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/socialWhite.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setContentAreaFilled(false);

        btnClientAlta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnClientAlta.setText("Alta / Baja");
        btnClientAlta.setContentAreaFilled(false);

        btnClientConsulta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClientConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnClientConsulta.setText("Consulta");
        btnClientConsulta.setContentAreaFilled(false);
        btnClientConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientConsultaActionPerformed(evt);
            }
        });

        btnVendedores.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVendedores.setForeground(new java.awt.Color(255, 255, 255));
        btnVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/business.png"))); // NOI18N
        btnVendedores.setText("Vendedores");
        btnVendedores.setContentAreaFilled(false);

        btnVendAlta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVendAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnVendAlta.setText("Alta / Baja");
        btnVendAlta.setContentAreaFilled(false);

        btnVendConsulta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVendConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnVendConsulta.setText("Consulta");
        btnVendConsulta.setContentAreaFilled(false);
        btnVendConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnPropiedades)
                        .addComponent(btnClientAlta)
                        .addComponent(btnClientConsulta)
                        .addComponent(btnVendAlta)
                        .addComponent(btnVendConsulta)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnNuevaPropiedad)
                            .addComponent(btnPropConsulta)))
                    .addComponent(btnClientes)
                    .addComponent(btnVendedores))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnPropiedades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPropConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnNuevaPropiedad)
                .addGap(27, 27, 27)
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnClientAlta)
                .addGap(30, 30, 30)
                .addComponent(btnVendedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnVendAlta)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        PanelVistas.setBackground(new java.awt.Color(255, 255, 255));
        PanelVistas.setLayout(new java.awt.CardLayout());
        getContentPane().add(PanelVistas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPropConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropConsultaActionPerformed
        // TODO add your handling code here:
        cardLayout.show(this.PanelVistas, "Consulta");
        PanelVistas.repaint();
    }//GEN-LAST:event_btnPropConsultaActionPerformed

    private void btnClientConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientConsultaActionPerformed

    private void btnVendConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVendConsultaActionPerformed

    private void BtnNuevaPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevaPropiedadActionPerformed
        // TODO add your handling code here:
        NuevaPropiedad nueva = new NuevaPropiedad();
        nueva.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        nueva.setVisible(true);
    }//GEN-LAST:event_BtnNuevaPropiedadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNuevaPropiedad;
    private javax.swing.JPanel PanelVistas;
    private javax.swing.JButton btnClientAlta;
    private javax.swing.JButton btnClientConsulta;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnPropConsulta;
    private javax.swing.JButton btnPropiedades;
    private javax.swing.JButton btnVendAlta;
    private javax.swing.JButton btnVendConsulta;
    private javax.swing.JButton btnVendedores;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
